'use client'

import React, { useState, useCallback, useRef } from 'react'
import {
  ReactFlow,
  ReactFlowProvider,
  addEdge,
  useNodesState,
  useEdgesState,
  Controls,
  Background,
  Node,
  Edge,
  Connection,
  Handle,
  Position
} from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { Trash2, Share2, MessageSquare, FileText, Database, Users, Zap, Cpu } from 'lucide-react'

// --- Custom Nodes ---

const nodeStyles: Record<string, any> = {
  sharepoint: { background: '#0369a1', border: '#bae6fd' }, // Sky/Ocean
  teams: { background: '#4c1d95', border: '#ddd6fe' }, // Violet
  powerAutomate: { background: '#1e40af', border: '#bfdbfe' }, // Blue
  powerApps: { background: '#86198f', border: '#f0abfc' }, // Fuchsia
  entra: { background: '#0f172a', border: '#94a3b8' }, // Slate
}

const iconMap: Record<string, React.ReactNode> = {
  sharepoint: <Database size={20} />,
  teams: <MessageSquare size={20} />,
  powerAutomate: <Zap size={20} />,
  powerApps: <Cpu size={20} />,
  entra: <Users size={20} />,
}

const labelMap: Record<string, string> = {
  sharepoint: 'SharePoint',
  teams: 'Microsoft Teams',
  powerAutomate: 'Power Automate',
  powerApps: 'Power Apps',
  entra: 'Entra ID',
}

const CustomNode = ({ data, type }: any) => {
  const style = nodeStyles[data.serviceType] || {
    background: '#334155',
    border: '#cbd5e1',
  }

  return (
    <div
      className="m365-node"
      style={{
        backgroundColor: style.background,
        borderColor: style.border,
      }}
    >
      <div className="m365-node-icon">
        {iconMap[data.serviceType] || <FileText size={20} />}
      </div>
      <div className="m365-node-text">
        <div className="m365-node-title">
          {labelMap[data.serviceType] || 'Service'}
        </div>
        <div className="m365-node-subtitle">{data.label}</div>
      </div>
      
      <Handle type="target" position={Position.Left} style={{ background: '#cbd5e1', width: '8px', height: '8px', border: 'none' }} />
      <Handle type="source" position={Position.Right} style={{ background: '#38bdf8', width: '8px', height: '8px', border: 'none' }} />
    </div>
  )
}

const initialNodes: Node[] = [
  { id: '1', type: 'custom', position: { x: 250, y: 100 }, data: { label: 'Doc Library', serviceType: 'sharepoint' } },
  { id: '2', type: 'custom', position: { x: 250, y: 250 }, data: { label: 'Approval Flow', serviceType: 'powerAutomate' } },
]
const initialEdges: Edge[] = [{ id: 'e1-2', source: '1', target: '2', animated: true, style: { stroke: '#38bdf8', strokeWidth: 2 } }]

let id = 0;
const getId = () => `dndnode_${id++}`;

export default function ArchitectureCanvasClient({ tool }: { tool: any }) {
  const reactFlowWrapper = useRef<HTMLDivElement>(null)
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes)
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges)
  const [reactFlowInstance, setReactFlowInstance] = useState<any>(null)
  const [markdownOutput, setMarkdownOutput] = useState('')

  const onConnect = useCallback(
    (params: Connection) => setEdges((eds) => addEdge({ ...params, animated: true, style: { stroke: '#38bdf8', strokeWidth: 2 } }, eds)),
    [setEdges]
  )

  const onDragStart = (event: React.DragEvent, nodeType: string) => {
    event.dataTransfer.setData('application/reactflow', nodeType)
    event.dataTransfer.effectAllowed = 'move'
  }

  const onDragOver = useCallback((event: React.DragEvent) => {
    event.preventDefault()
    event.dataTransfer.dropEffect = 'move'
  }, [])

  const onDrop = useCallback(
    (event: React.DragEvent) => {
      event.preventDefault()

      if (!reactFlowWrapper.current || !reactFlowInstance) return

      const type = event.dataTransfer.getData('application/reactflow')

      if (typeof type === 'undefined' || !type) {
        return
      }

      const position = reactFlowInstance.screenToFlowPosition({
        x: event.clientX,
        y: event.clientY,
      })

      const newNode: Node = {
        id: getId(),
        position,
        data: { label: `New ${labelMap[type]}`, serviceType: type },
        type: 'custom'
      }

      setNodes((nds) => nds.concat(newNode))
    },
    [reactFlowInstance, setNodes]
  )

  const clearCanvas = () => {
    setNodes([])
    setEdges([])
    setMarkdownOutput('')
  }

   const generateMarkdown = () => {
    let md = `# M365 Architecture Design\n\nGenerated by ImRizwan Tools on ${new Date().toLocaleDateString()}\n\n## Components\n\n`
    if (nodes.length === 0) {
      md += `*No components defined.*\n`
    } else {
        nodes.forEach(n => { md += `- **${labelMap[n.data.serviceType as string] || 'Node'}**: ${n.data.label} (ID: ${n.id})\n` })
    }
    md += `\n## Data Flow & Integration\n\n`
    if (edges.length === 0) {
        md += `*No connections defined.*\n`
    } else {
        edges.forEach(e => {
            const sourceNode = nodes.find(n => n.id === e.source)
            const targetNode = nodes.find(n => n.id === e.target)
            if (sourceNode && targetNode) {
                md += `- **${sourceNode.data.label}** (${labelMap[sourceNode.data.serviceType as string]})  -- triggers -->  **${targetNode.data.label}** (${labelMap[targetNode.data.serviceType as string]})\n`
            }
        })
    }
    setMarkdownOutput(md)
  }

  return (
    <div className="m365-wrapper">
      <style>{`
        .m365-wrapper {
          display: flex;
          flex-direction: column;
          gap: var(--space-6);
        }
        .m365-container {
          background: var(--bg-card);
          border: 1px solid var(--border);
          border-radius: var(--radius-xl);
          overflow: hidden;
          display: flex;
          flex-direction: column;
          box-shadow: var(--shadow-lg);
          height: 600px;
        }
        @media (min-width: 768px) {
          .m365-container { flex-direction: row; }
        }
        .m365-sidebar {
          width: 100%;
          background: var(--bg-secondary);
          border-right: 1px solid var(--border);
          padding: var(--space-4);
          display: flex;
          flex-direction: column;
          gap: var(--space-4);
          overflow-y: auto;
        }
        @media (min-width: 768px) {
          .m365-sidebar { width: 280px; }
        }
        .m365-toolbox-title {
          font-size: var(--fs-sm);
          font-weight: var(--fw-bold);
          text-transform: uppercase;
          letter-spacing: 0.1em;
          color: var(--text-muted);
          margin-bottom: var(--space-2);
        }
        .m365-toolbox-desc {
          font-size: var(--fs-xs);
          color: var(--text-secondary);
          margin-bottom: var(--space-2);
        }
        .m365-draggable {
          padding: var(--space-3);
          background: var(--glass-bg);
          border: 1px solid var(--border);
          border-radius: var(--radius-lg);
          display: flex;
          align-items: center;
          gap: var(--space-3);
          cursor: grab;
          transition: all var(--transition-fast);
        }
        .m365-draggable:hover {
          background: var(--bg-card);
          border-color: var(--accent);
          transform: translateY(-2px);
        }
        .m365-draggable span {
          font-size: var(--fs-sm);
          font-weight: var(--fw-medium);
          color: var(--text-primary);
        }
        .m365-actions {
          margin-top: auto;
          border-top: 1px solid var(--border);
          padding-top: var(--space-4);
          display: flex;
          flex-direction: column;
          gap: var(--space-2);
        }
        .m365-btn {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: var(--space-2);
          width: 100%;
          padding: var(--space-3);
          border-radius: var(--radius-lg);
          font-weight: var(--fw-semibold);
          font-size: var(--fs-sm);
          cursor: pointer;
          transition: all var(--transition-fast);
          border: 1px solid transparent;
        }
        .m365-btn-primary {
          background: var(--accent);
          color: white;
          box-shadow: 0 2px 12px var(--accent-glow);
        }
        .m365-btn-primary:hover {
          background: var(--accent-hover);
          transform: translateY(-2px);
          box-shadow: 0 4px 20px var(--accent-glow);
        }
        .m365-btn-secondary {
          background: var(--bg-secondary);
          color: var(--text-primary);
          border-color: var(--border);
        }
        .m365-btn-secondary:hover {
          background: var(--bg-card);
          border-color: var(--accent);
          color: var(--accent);
          transform: translateY(-2px);
        }
        .m365-canvas {
          flex: 1;
          height: 100%;
          background: var(--bg-primary);
        }
        .m365-node {
          padding: 12px 16px;
          border-radius: var(--radius-xl);
          border: 1px solid;
          display: flex;
          align-items: center;
          gap: 12px;
          color: white;
          min-width: 180px;
          box-shadow: var(--shadow-lg);
          transition: transform var(--transition-fast);
        }
        .m365-node:hover {
          transform: scale(1.02);
        }
        .m365-node-icon {
          padding: 8px;
          background: rgba(255, 255, 255, 0.15);
          border-radius: var(--radius-md);
          display: flex;
          align-items: center;
          justify-content: center;
        }
        .m365-node-title {
          font-weight: var(--fw-bold);
          font-size: var(--fs-sm);
        }
        .m365-node-subtitle {
          font-size: var(--fs-xs);
          opacity: 0.8;
          margin-top: 2px;
        }
        .m365-output {
          background: var(--bg-card);
          border: 1px solid var(--border);
          border-radius: var(--radius-xl);
          padding: var(--space-6);
        }
        .m365-output-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: var(--space-4);
        }
        .m365-output-title {
          font-size: var(--fs-lg);
          font-weight: var(--fw-bold);
          color: var(--text-primary);
          display: flex;
          align-items: center;
          gap: var(--space-2);
        }
        .m365-copy-btn {
          font-size: var(--fs-sm);
          color: var(--text-primary);
          background: var(--bg-secondary);
          border: 1px solid var(--border);
          padding: var(--space-2) var(--space-4);
          border-radius: var(--radius-md);
          cursor: pointer;
          display: flex;
          align-items: center;
          gap: var(--space-2);
          transition: all var(--transition-fast);
        }
        .m365-copy-btn:hover {
          background: var(--bg-card);
          border-color: var(--accent);
          color: var(--accent);
        }
        .m365-pre {
          background: var(--bg-code);
          padding: var(--space-4);
          border-radius: var(--radius-lg);
          border: 1px solid var(--border);
          overflow-x: auto;
          color: var(--text-primary);
          font-family: var(--font-mono);
          font-size: var(--fs-sm);
        }
      `}</style>
      
      <div className="m365-container reveal">
        <div className="m365-sidebar">
          <div>
            <div className="m365-toolbox-title">Toolbox</div>
            <p className="m365-toolbox-desc">Drag components onto the canvas below.</p>
          </div>
          
          <div className="m365-draggable" draggable onDragStart={(e) => onDragStart(e, 'sharepoint')}>
            <Database style={{ color: '#0ea5e9' }} size={20}/>
            <span>SharePoint</span>
          </div>
          <div className="m365-draggable" draggable onDragStart={(e) => onDragStart(e, 'powerAutomate')}>
            <Zap style={{ color: '#3b82f6' }} size={20}/>
            <span>Power Automate</span>
          </div>
          <div className="m365-draggable" draggable onDragStart={(e) => onDragStart(e, 'powerApps')}>
            <Cpu style={{ color: '#d946ef' }} size={20}/>
            <span>Power Apps</span>
          </div>
          <div className="m365-draggable" draggable onDragStart={(e) => onDragStart(e, 'teams')}>
            <MessageSquare style={{ color: '#8b5cf6' }} size={20}/>
            <span>Teams</span>
          </div>
          <div className="m365-draggable" draggable onDragStart={(e) => onDragStart(e, 'entra')}>
            <Users style={{ color: '#94a3b8' }} size={20}/>
            <span>Entra ID</span>
          </div>

          <div className="m365-actions">
            <button onClick={clearCanvas} className="m365-btn m365-btn-secondary">
              <Trash2 size={16}/> Clear
            </button>
            <button onClick={generateMarkdown} className="m365-btn m365-btn-primary">
              <FileText size={16}/> Generate Docs
            </button>
          </div>
        </div>

        <div className="m365-canvas" ref={reactFlowWrapper}>
          <ReactFlowProvider>
            <ReactFlow
              nodes={nodes}
              edges={edges}
              nodeTypes={{ custom: CustomNode }}
              onNodesChange={onNodesChange}
              onEdgesChange={onEdgesChange}
              onConnect={onConnect}
              onInit={setReactFlowInstance}
              onDrop={onDrop}
              onDragOver={onDragOver}
              fitView
              colorMode="dark"
            >
              <Background gap={16} />
              <Controls />
            </ReactFlow>
          </ReactFlowProvider>
        </div>
      </div>

      {markdownOutput && (
        <div className="m365-output reveal">
           <div className="m365-output-header">
              <h3 className="m365-output-title">
                  <FileText color="#38bdf8"/> Generated Architecture Document
              </h3>
              <button onClick={() => navigator.clipboard.writeText(markdownOutput)} className="m365-copy-btn">
                <Share2 size={16}/> Copy
              </button>
           </div>
           <pre className="m365-pre">
               <code>{markdownOutput}</code>
           </pre>
        </div>
      )}
    </div>
  )
}
